# Site settings
title: Jessica F Raines
email: jessicafraines@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  'All growth depends upon activity. There is no development physically or intellectually without effort, and effort means work.'
  <br/> 
  <cite>--Calvin Coolidge</cite>

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jessicafraines.github.io"
twitter_username: jescafaith
github_username: jessicafraines

# Build settings
markdown: kramdown
